on:
  schedule:
    - cron:  '0 0 * * *'

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Read .nvmrc into variable
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Use Node Version in .nvmrc
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Yarn Install
        run: yarn

      - name: Check Source
        run: yarn check-source